### ISSUE TITLE
消息换行

### ISSUE THREAD

**Issue by lywly** [easychen/wecomchan#10]
大佬们：
- `README.md`中的PHP版本发送"推送测试\r\n测试换行"可以正常换行；
- 服务器部署PHP版本后，发送消息不支持换行（`https://x.xxx.xxx/?sendkey=sendkey&text=推送测试\r\n测试换行`）
有人遇到这个问题吗？求助

**Comment by easychen** [comment]
text 通过 get 方法传递时需要先 urlencode

**Comment by lywly** [comment]
#### 以下信息给需要的朋友们参考：
---
- `\r\n`使用UrlEncode编码后的字符为`%5Cr%5Cn`，实测并不能换行；
- 尝试后发现可使用`%0D%0A`实现换行。
