### ISSUE TITLE
腾讯报错

### ISSUE THREAD

**Issue by rq1025330** [easychen/wecomchan#18]
{"errorCode":1,"errorMessage":"Process exited before completing request","requestId":"954a3c773d9e987c100b46927b4d01d5","statusCode":439}

**Comment by jihu9** [comment]
> {"errorCode":1,"errorMessage":"Process exited before completing request","requestId":"954a3c773d9e987c100b46927b4d01d5","statusCode":439}

我也有这个问题，不知如何是好

**Comment by rq1025330** [comment]
url转码

**Comment by jihu9** [comment]
> url转码

重新调整了并发配额，现在已经可以了
