### ISSUE TITLE
docker启动失败

### ISSUE THREAD

**Issue by rq1025330** [easychen/wecomchan#19]
![image](https://user-images.githubusercontent.com/52870887/124565548-bc338e00-de74-11eb-93b8-7a4abaf8dfcd.png)
启动失败不能用

**Comment by rq1025330** [comment]
![image](https://user-images.githubusercontent.com/52870887/124566248-77f4bd80-de75-11eb-8607-df724edd9111.png)

**Comment by rq1025330** [comment]
是
![image](https://user-images.githubusercontent.com/52870887/124574265-dffad200-de7c-11eb-97b9-88728886437e.png)
这个原因？  我是arm

**Comment by AceAttorney** [comment]
> 是
> ![image](https://user-images.githubusercontent.com/52870887/124574265-dffad200-de7c-11eb-97b9-88728886437e.png)
> 这个原因？ 我是arm

应该是 这个暂时没做对应arm平台的镜像 我这边没有arm设备 可能涉及交叉编译 后面看一下

@rq1025330 发下你平台的具体信息，我有空了试一下

**Comment by rq1025330** [comment]
我是斐讯N1 晶晨Amlogic S905D  还有HK1 晶晨Amlogic s905x3 都是软路由Openwrt 装的docker
![image](https://user-images.githubusercontent.com/52870887/124622843-084ef480-deae-11eb-8e45-7c6125e65265.png)

**Comment by AceAttorney** [comment]
> 我是斐讯N1 晶晨Amlogic S905D 还有HK1 晶晨Amlogic s905x3 都是软路由Openwrt 装的docker
> ![image](https://user-images.githubusercontent.com/52870887/124622843-084ef480-deae-11eb-8e45-7c6125e65265.png)

这个信息还是不能帮我确定具体架构，搜了下暂时按linux/arm64 架构处理，已经添加了该架构的镜像，请删除本地已存在的镜像，重新拉镜像尝试，应该会匹配，如有问题请继续回复本issus。

@rq1025330

**Comment by rq1025330** [comment]
测试已经可以成工运行

**Comment by AceAttorney** [comment]
@rq1025330 @easychen 等我把代码合并上来这个issue就可以关了

**Comment by rq1025330** [comment]
好 谢谢 , 这个公网就方便
