### ISSUE TITLE
云函数不支持post请求

### ISSUE THREAD

**Issue by classccai** [easychen/wecomchan#23]
默认的HTTP请求只支持GET，当参数过长时，云函数报参数过长错误
错误如下：
`StatusCodeError: 414 - "<html>\r\n<head><title>414 Request-URI Too Large</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>414 Request-URI Too Large</h1></center>\r\n<hr><center>apigw/1.0.16_1.3.3</center>\r\n</body>\r\n</html>\r\n"`

**Comment by riba2534** [comment]
后续会考虑添加POST请求

**Comment by riba2534** [comment]
> 默认的HTTP请求只支持GET，当参数过长时，云函数报参数过长错误
> 错误如下：
> `StatusCodeError: 414 - "<html>\r\n<head><title>414 Request-URI Too Large</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>414 Request-URI Too Large</h1></center>\r\n<hr><center>apigw/1.0.16_1.3.3</center>\r\n</body>\r\n</html>\r\n"`

云函数现已支持 POST 请求，请下载最新的二进制文件，使用文档见：https://github.com/riba2534/wecomchan/tree/main/go-scf#%E4%BD%BF%E7%94%A8-post-%E8%BF%9B%E8%A1%8C%E8%AF%B7%E6%B1%82
