### ISSUE TITLE
云函数报错

### ISSUE THREAD

**Issue by jihu9** [easychen/wecomchan#24]
{"errorCode":1,"errorMessage":"Resource limit exceed for function [dingdong]","requestId":"1a04a1006a8d321f05031308b4fd695d","statusCode":432}

**Comment by riba2534** [comment]
云函数相关问题记得at我一下。你这个问题可以搜索解决，https://cloud.tencent.com/document/product/583/9180


![image](https://user-images.githubusercontent.com/26398978/125627985-c9423375-be82-4922-a776-e17e56f0647b.png)

**Comment by jihu9** [comment]
> 云函数相关问题记得at我一下。你这个问题可以搜索解决，https://cloud.tencent.com/document/product/583/9180
> 
> 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/26398978/125627985-c9423375-be82-4922-a776-e17e56f0647b.png)
> 
> 
> 
> 

是的，自己解决了，非常感谢
