### ISSUE TITLE
关于Python版本的send_to_wecom_image()函数，怎么也无法发送图片

### ISSUE THREAD

**Issue by ChanLicher** [easychen/wecomchan#44]
我输入某图片的base64编码后，函数总是在  if "media_id" in upload_response:  这个部分返回False。我没用过微信的API，我不太懂到底是哪里出问题了？

**Comment by MOldtime** [comment]
同问 有解决吗

**Comment by easychen** [comment]
> 我输入某图片的base64编码后，函数总是在 if "media_id" in upload_response: 这个部分返回False。我没用过微信的API，我不太懂到底是哪里出问题了？

这是企业微信接口，不是微信api。文档在：https://developer.work.weixin.qq.com/document/path/90253  可以看到图片最大限制为10M。

> 同问 有解决吗

把 upload_response 打印出来看看返回了什么。

**Comment by MOldtime** [comment]
> > 我输入某图片的base64编码后，函数总是在 if "media_id" in upload_response: 这个部分返回False。我没用过微信的API，我不太懂到底是哪里出问题了？
> 
> 这是企业微信接口，不是微信api。文档在：https://developer.work.weixin.qq.com/document/path/90253 可以看到图片最大限制为10M。
> 
> > 同问 有解决吗
> 
> 把 upload_response 打印出来看看返回了什么。

我拿在IDE运行了下 图片发出来的是文件 上传貌似有问题 大概是少了文件后缀 因为使用Open()方法就可以正常

**Comment by MOldtime** [comment]
> > > 我输入某图片的base64编码后，函数总是在 if "media_id" in upload_response: 这个部分返回False。我没用过微信的API，我不太懂到底是哪里出问题了？
> > 
> > 
> > 这是企业微信接口，不是微信api。文档在：https://developer.work.weixin.qq.com/document/path/90253 可以看到图片最大限制为10M。
> > > 同问 有解决吗
> > 
> > 
> > 把 upload_response 打印出来看看返回了什么。
> 
> 我拿在IDE运行了下 图片发出来的是文件 上传貌似有问题 大概是少了文件后缀 因为使用Open()方法就可以正常

原来是我的base643有问题 太惨了 找半天问题
