### ISSUE TITLE
有办法让群员不暴露真实姓名与手机号吗

### ISSUE THREAD

**Issue by tkkcc** [easychen/wecomchan#53]
[通讯录管理](https://work.weixin.qq.com/wework_admin/frame#profile/contactsMng)中的 全体成员信息显示与互联企业成员资料显示 中 姓名必须勾选，有使用别名的方法吗。只想用作推送，不希望群员之间知道彼此真实姓名。

**Comment by tkkcc** [comment]
好像可以不启用全员群与部门群。还可以在通讯录查看权限中 隐藏的部门/成员 限制查看外部门 限制查看所有人都把群选上。

**Comment by tkkcc** [comment]
但是个人申请的只能有200人群，意味着只能向200个用户推送？

**Comment by easychen** [comment]
> 但是个人申请的只能有200人群，意味着只能向200个用户推送？

是的，但你可以申请多个企业。

**Comment by tkkcc** [comment]
谢谢
