### ISSUE TITLE
请求支持 HW的函数工作流,这个又百万的免费调用.比良心云良心

### ISSUE THREAD

**Issue by gaoyuoppa** [easychen/wecomchan#54]

**Comment by gaoyuoppa** [comment]
又>有

**Comment by gaoyuoppa** [comment]
良心云黑化了,开始收费了...

![3cb46d22649e7f6deb7d173b0352a690](https://user-images.githubusercontent.com/20106653/164888845-e92eef51-1812-4182-a30d-d2008c6f2a95.jpeg)

**Comment by Colo-Thor** [comment]
go语言版：https://github.com/Colo-Thor/wecomchan/releases/tag/2.2
