### ISSUE TITLE
docker版怎么用POST请求发送文本消息

### ISSUE THREAD

**Issue by ansemz** [easychen/wecomchan#57]
\# curl -X POST  -d '{"sendkey":"mysendkey","msg_type":"text","msg":"test msg"}' 'http://localhost:48080/wecomchan'
curl: (52) Empty reply from server
查看wecomchan的日志
2022/05/10 01:23:33 wecomchan.go:94: 企业微信获取access_token接口返回==> map[access_token:a_valid_token errcode:0 errmsg:ok expires_in:7200]
2022/05/10 01:23:33 wecomchan.go:248: sendkey 错误，请检查
2022/05/10 01:23:33 server.go:3139: http: panic serving 172.17.0.1:40915: sendkey 错误，请检查

请问大佬是docker版的不支持POST发送文本消息吗？
不支持的话能不能增加这个功能呢？现实情况下，消息可能会有很多行，用GET发送实在太不方便了。
万分感谢

**Comment by sola97** [comment]
我自己改的支持post的docker [docker-compose.yml](https://github.com/sola97/wecomchan/blob/main/go-wecomchan/docker-compose.yml)

**Comment by ansemz** [comment]
> 我自己改的支持post的docker [docker-compose.yml](https://github.com/sola97/wecomchan/blob/main/go-wecomchan/docker-compose.yml)

非常感谢，测试成功了。留个例子给有同样需求的同学。
curl -H 'Content-Type: application/json' -d '{"sendkey":"mykey","msg":"post_test","msg_type":"text"}' 'http://127.0.0.1:18080/wecomchan'
