### ISSUE TITLE
做了一个类似的项目，希望参与serverchan生态建设

### ISSUE THREAD

**Issue by LeslieLeung** [easychen/wecomchan#63]
https://github.com/LeslieLeung/notification-gateway-lite

目前推送渠道已经支持
- [Bark](https://github.com/Finb/Bark)
- [企业微信应用消息](https://developer.work.weixin.qq.com/document/path/90236)
- [企业微信机器人webhook](https://developer.work.weixin.qq.com/document/path/91770)
- [PushDeer](http://pushdeer.com/)
- [Pushover](https://pushover.net/api)

同时还支持腾讯云、阿里云的serverless部署，感觉会是本项目一个很好的补充。

**Comment by easychen** [comment]
挺不错的项目，可以参考下 apprise，已经整合了上百个通道了。 https://github.com/caronc/apprise
