### ISSUE TITLE
请教百度云版本如何发送超链接

### ISSUE THREAD

**Issue by BenjiaH** [easychen/wecomchan#65]
请教百度云版本如何发送超链接？
例如网址超链接:
[网址](https://www.baidu.com)

@mapxn

**Comment by mapxn** [comment]
@BenjiaH 你好，文本超链接可以发这样的请求使用
```json
{
    "key": "yourSendKey",
    "type": "text",
    "msg": "这里支持<a href=\"https://www.baidu.com/\">文本中支持超链接</a>"
}
```

**Comment by BenjiaH** [comment]
> @BenjiaH 你好，文本超链接可以发这样的请求使用
> 
> ```json
> 
> {
> 
>     "key": "yourSendKey",
> 
>     "type": "text",
> 
>     "msg": "这里支持<a href=\"https://www.baidu.com/\">文本中支持超链接</a>"
> 
> }
> 
> ```
> 
> 

好的，谢谢
