### ISSUE TITLE
弱弱问一下，已经有企业微信群机器人了，为什么还要用这个呢

### ISSUE THREAD

**Issue by wei-z-git** [easychen/wecomchan#67]
刚注册了企业微信，发现企业微信群bot已经有丰富的api用来推送消息到微信，所以有一点不解为什么我们还需要用这个基于微信插件的bot来推送消息呢

是因为群聊bot的api调用次数有限制吗，求大佬解答(*╹▽╹*)

**Comment by easychen** [comment]
企业微信群的机器人发布的消息在微信客户端没有提示音。

**Comment by wei-z-git** [comment]
sorry我看错了，确实没声音，这个通知是企业微信client的   /捂脸

> 
> hi 大佬  @easychen
> 刚试默认有声音通知的，MI8 Android12 PixelExperience
> 
> 但是缺点是没法像微信插件一样@人
> ![dfafc3e982c412f118482f93ac2c558](https://user-images.githubusercontent.com/32572815/184047300-4a1889f9-1b2c-49e0-890a-a32cc3aa7524.jpg)
> 
>
