### ISSUE TITLE
PHP 版能否使用 post 参数

### ISSUE THREAD

**Issue by rockbenben** [easychen/wecomchan#68]
能不能用 post 方式使用 wecom 酱的 php 版本

post body 为{"msg": "post_test","test": "text1"}，php 设置为`echo send_to_wecom(@$_POST['msg'], WECOM_CID, WECOM_AID, WECOM_SECRET, WECOM_TOUID);`

尝试过下列修改：
- php 配置 enable_post_data_reading=on
- `$raw = file_get_contents('php://input'); echo $raw;` 
- hearder 修改 `Content-Type=application/x-www-data-urlencoded`

但是，均提示 `empty content`，无法从 $_POST['msg'] 获取数值。

**Comment by easychen** [comment]
默认就支持 post，但是你的body要用 form-urlencoded 格式，不能用json。
