### ISSUE TITLE
Server酱logo图 挂掉了

### ISSUE THREAD

**Issue by PSC-F** [easychen/wecomchan#8]
https://theseven.ftqq.com/20210208142819.png

http code 403

**Comment by PSC-F** [comment]
logo

**Comment by easychen** [comment]
防盗链了。直接输入URL 访问吧

**Comment by maxoyed** [comment]
![image](https://user-images.githubusercontent.com/25519245/127769785-4c99638f-9f76-4ba0-95c1-128f1979686c.png)
