### ISSUE TITLE
Bad  params输入网址显示这个，用测试内容，闪一下不现实东西

### ISSUE THREAD

**Issue by taoqiko** [easychen/wecomchan#9]
Bad  params输入网址显示这个，用测试内容，闪一下网页不显示东西，微信也没有消息的。这个是什么问题呢。

**Comment by fejich** [comment]
`sendkey` 需要在 php 文件里边手动编辑下，这个相当于 token 
`http://指向运行环境的域名/?sendkey=你设定的sendkey&text=你要发送的内容`

正常工作会返回下面的结果
`{"errcode":0,"errmsg":"ok","invaliduser":""}`

**Comment by taoqiko** [comment]
是的，我再php里编辑里sendkey，然后用http://指向运行环境的域名/?sendkey=你设定的sendkey&text=你要发送的内容，但是只闪一下，界面是空白的，没有显示内容

**Comment by vlanbin** [comment]
可以检查一下企业ID和应用Secret是否有误，还有就是运行环境。我这边PHP7.4下是可以正常使用的

**Comment by taoqiko** [comment]
我用的宝塔，然后专门搞的php7.4，应用id的话，原来在server酱那里用过。纳闷了。

**Comment by easychen** [comment]
curl 装了么？

**Comment by taoqiko** [comment]
curl肯定装的，服务器用的阿里云的轻量，环境这块常用的都安装了。

**Comment by fejich** [comment]
我在 `挖站否免费PHP空间` 部署了一个，目前一切正常

本地机器用 Docker 跑 `linuxserver/nginx` 容器测试下来也ok

**Comment by taoqiko** [comment]
嗯，已经解决了，感谢

**Comment by mingjing99** [comment]
> 嗯，已经解决了，感谢

请问怎么解决的？我也有同样的问题，找不出原因？谢谢！

**Comment by cn0068** [comment]
> > 嗯，已经解决了，感谢
> 
> 请问怎么解决的？我也有同样的问题，找不出原因？谢谢！

把php版本改为7.4及以上就可以了
